development:
  sessions:
    default:
      database: twavatars
      hosts:
        - localhost:27017    
        
test:
  sessions:
    default:
      database: twavatars_test
      hosts:
        - localhost:27017
        
production:
  uri: <%= ENV['MONGOLAB_URI'] %>